version: '3.4'
services:
  web:
    build:
      context: ./
      args:
        YOTI_BASE_URL: "${YOTI_BASE_URL}"
        YOTI_CLIENT_SDK_ID: "${YOTI_CLIENT_SDK_ID}"
        YOTI_KEY_FILE_PATH: "${YOTI_KEY_FILE_PATH}"
    ports:
      - "8000:8000"
